InventarioIFSP/InventarioIFSP/Models/Item.cs
using InventarioIFSP.Database;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventarioIFSP.Models
{
    public class Item
    {
        public int ID { get; set; }

        [Display(Name = "Patrimônio")]
        public string Patrimonio { get; set; }
        public ItemCategoria Categoria { get; set; }
        public Localidade Localidade { get; set; }
        public ItemStatus Status{ get; set; } // Cadastro BD

        [Display(Name = "Observação")]
        public string Observacao { get; set; } = "";
        public IEnumerable<SelectListItem> Tipos_Status { get; set; }
        public IEnumerable<SelectListItem> Localidades { get; set; }
        public IEnumerable<SelectListItem> Categorias { get; set; }

    }
}

InventarioIFSP/InventarioIFSP/Controllers/ItemController.cs
using InventarioIFSP.Database;
using InventarioIFSP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventarioIFSP.Controllers
{
    public class ItemController : Controller
    {

        [HttpGet]
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }
        
        [HttpGet]
        public ActionResult Create()
        {
            // Início: Proteção de rota
            if (Session["usuario_nivel"] == null)
            {
                TempData["msg"] = "Necessário estar logado!";
                TempData["msg_type"] = "warning";
                return RedirectToAction("Index", "Home");
            }

            if (Convert.ToInt32(Session["usuario_nivel"]) > 1)
            {
                TempData["msg"] = "Você não tem autorização para acessar esta área!";
                TempData["msg_type"] = "danger";
                return RedirectToAction("Index", "Home");
            }
            // Fim: Proteção de Rota

            LocalidadeDAO.AtualizaLocalidades();
            ItemCategoriaDAO.AtualizaCategorias();
            ItemStatusDAO.AtualizaTiposStatus();
            return View();
        }

        [HttpPost]
        public ActionResult Create(Item item)
        {
            // Início: Proteção de rota
            if (Session["usuario_nivel"] == null)
            {
                TempData["msg"] = "Necessário estar logado!";
                TempData["msg_type"] = "warning";
                return RedirectToAction("Index", "Home");
            }

            if (Convert.ToInt32(Session["usuario_nivel"]) > 1)
            {
                TempData["msg"] = "Você não tem autorização para acessar esta área!";
                TempData["msg_type"] = "danger";
                return RedirectToAction("Index", "Home");
            }
            // Fim: Proteção de Rota

            try
            {
                try
                {
                    if (item.Observacao.Equals(string.Empty)) { }
                }
                catch (Exception)
                {
                    string str = "";
                    item.Observacao = str;
                }
                if(ItemDAO.Create(item) != null)
                {
                    TempData["msg"] = "Criado com sucesso!";
                    TempData["msg_type"] = "success";
                    return RedirectToAction("Index");
                }
            }
            catch
            {
            }
            TempData["msg"] = "Erro ao criar!";
            TempData["msg_type"] = "danger";
            return View();
        }

        [HttpGet]
        public ActionResult List()
        {
            // Início: Proteção de rota
            if (Session["usuario_nivel"] == null)
            {
                TempData["msg"] = "Necessário estar logado!";
                TempData["msg_type"] = "warning";
                return RedirectToAction("Index", "Home");
            }

            if (Convert.ToInt32(Session["usuario_nivel"]) > 1)
            {
                TempData["msg"] = "Você não tem autorização para acessar esta área!";
                TempData["msg_type"] = "danger";
                return RedirectToAction("Index", "Home");
            }
            // Fim: Proteção de Rota

            try
            {
                LocalidadeDAO.AtualizaLocalidades();
                ItemCategoriaDAO.AtualizaCategorias();
                ItemStatusDAO.AtualizaTiposStatus();
                List<Item> lista = ItemDAO.GetAll();
                TempData["lista_status"] = ItemStatusDAO.lista_status;
                return View(lista);
            }
            catch
            {
                TempData["msg"] = "Erro ao buscar dados!";
                TempData["msg_type"] = "danger";
                return View();
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            // Início: Proteção de rota
            if (Session["usuario_nivel"] == null)
            {
                TempData["msg"] = "Necessário estar logado!";
                TempData["msg_type"] = "warning";
                return RedirectToAction("Index", "Home");
            }

            if (Convert.ToInt32(Session["usuario_nivel"]) > 1)
            {
                TempData["msg"] = "Você não tem autorização para acessar esta área!";
                TempData["msg_type"] = "danger";
                return RedirectToAction("Index", "Home");
            }
            // Fim: Proteção de Rota

            try
            {
                LocalidadeDAO.AtualizaLocalidades();
                ItemCategoriaDAO.AtualizaCategorias();
                ItemStatusDAO.AtualizaTiposStatus();
                Item item = ItemDAO.GetByID(id);
                if (item != null)
                {
                    return View(item);
                }
            }
            catch (Exception)
            {
            }
            TempData["msg"] = "Erro ao buscar dados!";
            TempData["msg_type"] = "danger";
            return View();
        }

        [HttpPost]
        public ActionResult Edit(Item item)
        {
            // Início: Proteção de rota
            if (Session["usuario_nivel"] == null)
            {
                TempData["msg"] = "Necessário estar logado!";
                TempData["msg_type"] = "warning";
                return RedirectToAction("Index", "Home");
            }

            if (Convert.ToInt32(Session["usuario_nivel"]) > 1)
            {
                TempData["msg"] = "Você não tem autorização para acessar esta área!";
                TempData["msg_type"] = "danger";
                return RedirectToAction("Index", "Home");
            }
            // Fim: Proteção de Rota

            try
            {
                try
                {
                    if (item.Observacao.Equals(string.Empty)) { }
                }
                catch (Exception)
                {
                    string str = "";
                    item.Observacao = str;
                }
                if (ItemDAO.Update(item))
                {
                    TempData["msg"] = "Atualizado com sucesso!";
                    TempData["msg_type"] = "success";
                    return RedirectToAction("Index");
                }
            }
            catch
            {
            }
            TempData["msg"] = "Erro ao buscar dados!";
            TempData["msg_type"] = "danger";
            return View();
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            // Início: Proteção de rota
            if (Session["usuario_nivel"] == null)
            {
                TempData["msg"] = "Necessário estar logado!";
                TempData["msg_type"] = "warning";
                return RedirectToAction("Index", "Home");
            }

            if (Convert.ToInt32(Session["usuario_nivel"]) > 1)
            {
                TempData["msg"] = "Você não tem autorização para acessar esta área!";
                TempData["msg_type"] = "danger";
                return RedirectToAction("Index", "Home");
            }
            // Fim: Proteção de Rota

            try
            {
                if (ItemDAO.Delete(id))
                {
                    TempData["msg"] = "Atualizado com sucesso!";
                    TempData["msg_type"] = "success";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
            }
            TempData["msg"] = "Erro ao excluir!";
            TempData["msg_type"] = "danger";
            return RedirectToAction("Index");
        }

        // Esta action recebe os dados do ajax para atualizar os dados do inventario
        [HttpPost]
        public ActionResult AtualizaStatus()
        {
            int id = Convert.ToInt32(Request["id"]);
            int status = Convert.ToInt32(Request["status"]);
            Item item = ItemDAO.GetByID(id);
            item.Status.Id = status;
            if (ItemDAO.Update(item))
            {
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }

        // Esta action recebe os dados do ajax para atualizar os dados do inventario
        [HttpPost]
        public ActionResult AtualizaObs()
        {
            int id = Convert.ToInt32(Request["id"]);
            string observacao = Request["observacao"];
            Item item = ItemDAO.GetByID(id);
            item.Observacao = observacao;
            if (ItemDAO.Update(item))
            {
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Details(int id)
        {
            // Início: Proteção de rota
            if (Session["usuario_nivel"] == null)
            {
                TempData["msg"] = "Necessário estar logado!";
                TempData["msg_type"] = "warning";
                return RedirectToAction("Index", "Home");
            }

            if (Convert.ToInt32(Session["usuario_nivel"]) > 1)
            {
                TempData["msg"] = "Você não tem autorização para acessar esta área!";
                TempData["msg_type"] = "danger";
                return RedirectToAction("Index", "Home");
            }
            // Fim: Proteção de Rota
            try
            {
                Item item = ItemDAO.GetByID(id);
                return View("Details", item);
            }
            catch (Exception)
            {
                TempData["msg"] = "Erro ao buscar dados!";
                TempData["msg_type"] = "danger";
                return View();
            }
            
        }

InventarioIFSP/InventarioIFSP/Controllers/ItemStatusController.cs
using InventarioIFSP.Database;
using InventarioIFSP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventarioIFSP.Controllers
{
    public class ItemStatusController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult Create()
        {
            // Início: Proteção de rota
            if (Session["usuario_nivel"] == null)
            {
                TempData["msg"] = "Necessário estar logado!";
                TempData["msg_type"] = "warning";
                return RedirectToAction("Index", "Home");
            }

            if (Convert.ToInt32(Session["usuario_nivel"]) > 1)
            {
                TempData["msg"] = "Você não tem autorização para acessar esta área!";
                TempData["msg_type"] = "danger";
                return RedirectToAction("Index", "Home");
            }
            // Fim: Proteção de Rota

            return View();
        }

        [HttpPost]
        public ActionResult Create(ItemStatus cat)
        {
            // Início: Proteção de rota
            if (Session["usuario_nivel"] == null)
            {
                TempData["msg"] = "Necessário estar logado!";
                TempData["msg_type"] = "warning";
                return RedirectToAction("Index", "Home");
            }

            if (Convert.ToInt32(Session["usuario_nivel"]) > 1)
            {
                TempData["msg"] = "Você não tem autorização para acessar esta área!";
                TempData["msg_type"] = "danger";
                return RedirectToAction("Index", "Home");
            }
            // Fim: Proteção de Rota

            try
            {
                if (ItemStatusDAO.Create(cat) != null)
                {
                    TempData["msg"] = "Criado com sucesso!";
                    TempData["msg_type"] = "success";
                    return RedirectToAction("Index");

                }

            }
            catch
            {
            }
            TempData["msg"] = "Erro ao criar";
            TempData["msg_type"] = "danger";
            return View();
        }

        public ActionResult Edit(int id)
        {
            // Início: Proteção de rota
            if (Session["usuario_nivel"] == null)
            {
                TempData["msg"] = "Necessário estar logado!";
                TempData["msg_type"] = "warning";
                return RedirectToAction("Index", "Home");
            }

            if (Convert.ToInt32(Session["usuario_nivel"]) > 1)
            {
                TempData["msg"] = "Você não tem autorização para acessar esta área!";
                TempData["msg_type"] = "danger";
                return RedirectToAction("Index", "Home");
            }
            // Fim: Proteção de Rota

            try
            {
                ItemStatus cat = ItemStatusDAO.GetByID(id);
                if (cat != null)
                    return View(cat);
            }
            catch
            {
            }
            TempData["msg"] = "Erro ao buscar dados";
            TempData["msg_type"] = "danger";
            return View();
        }

        [HttpPost]
        public ActionResult Edit(ItemStatus status)
        {
            // Início: Proteção de rota
            if (Session["usuario_nivel"] == null)
            {
                TempData["msg"] = "Necessário estar logado!";
                TempData["msg_type"] = "warning";
                return RedirectToAction("Index", "Home");
            }

            if (Convert.ToInt32(Session["usuario_nivel"]) > 1)
            {
                TempData["msg"] = "Você não tem autorização para acessar esta área!";
                TempData["msg_type"] = "danger";
                return RedirectToAction("Index", "Home");
            }
            // Fim: Proteção de Rota

            try
            {
                if (ItemStatusDAO.Update(status))
                {
                    TempData["msg"] = "Alterado com sucesso!";
                    TempData["msg_type"] = "success";
                    return RedirectToAction("Index");
                }
            }
            catch
            {
            }
            TempData["msg"] = "Erro ao criar";
            TempData["msg_type"] = "danger";
            return View();
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            // Início: Proteção de rota
            if (Session["usuario_nivel"] == null)
            {
                TempData["msg"] = "Necessário estar logado!";
                TempData["msg_type"] = "warning";
                return RedirectToAction("Index", "Home");
            }

            if (Convert.ToInt32(Session["usuario_nivel"]) > 1)
            {
                TempData["msg"] = "Você não tem autorização para acessar esta área!";
                TempData["msg_type"] = "danger";
                return RedirectToAction("Index", "Home");
            }
            // Fim: Proteção de Rota

            try
            {
                if (ItemStatusDAO.Delete(id))
                {
                    TempData["msg"] = "Excluído com sucesso!";
                    TempData["msg_type"] = "success";
                    return RedirectToAction("List");
                }
            }
            catch
            {
            }
            TempData["msg"] = "Erro ao excluir";
            TempData["msg_type"] = "danger";
            return View();
        }

        [HttpGet]
        public ActionResult List()
        {
            // Início: Proteção de rota
            if (Session["usuario_nivel"] == null)
            {
                TempData["msg"] = "Necessário estar logado!";
                TempData["msg_type"] = "warning";
                return RedirectToAction("Index", "Home");
            }

            if (Convert.ToInt32(Session["usuario_nivel"]) > 1)
            {
                TempData["msg"] = "Você não tem autorização para acessar esta área!";
                TempData["msg_type"] = "danger";
                return RedirectToAction("Index", "Home");
            }
            // Fim: Proteção de Rota

            try
            {
                return View(ItemStatusDAO.GetAll());
            }
            catch
            {
                return View();
            }
        }
    }
}

InventarioIFSP/InventarioIFSP/Views/Item/Create.cshtml
@model InventarioIFSP.Models.Item

@{
    ViewBag.Title = "Criar novo item";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row justify-content-center">
    <h2>@ViewBag.Title</h2>
</div>

@{
    if (TempData["msg"] != null)
    {
        <div class="alert alert-@TempData["msg_type"] text-center">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            @TempData["msg"]
        </div>
    }

}
<div class="row justify-content-center">
    <div class="col-10">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Patrimonio, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Patrimonio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Patrimonio, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <span>
                        @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "control-label" })
                        @Html.ActionLink("+", "Create", "ItemCategoria", null, new { @class = "btn btn-sm btn-primary" })

                    </span>
                    @Html.DropDownListFor(
                                model => model.Categoria.ID,
                                InventarioIFSP.Database.ItemCategoriaDAO.lista_categorias,
                                new { @class = "form-control" }
                            )
                    @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @*@Html.LabelFor(model => model.Localidade, htmlAttributes: new { @class = "control-label" })*@
                    <label class="control-label" for="localidade">Localização</label>
                    @Html.DropDownListFor(
                                model => model.Localidade.ID,
                                InventarioIFSP.Database.LocalidadeDAO.lista_localidades,
                                new { @class = "form-control" }
                            )
                    @Html.ValidationMessageFor(model => model.Localidade, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <span>
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label" })
                        @Html.ActionLink("+", "Create", "ItemStatus", null, new { @class = "btn btn-sm btn-primary" })
                    </span>
                    @Html.DropDownListFor(
                                model => model.Status.Id,
                                InventarioIFSP.Database.ItemStatusDAO.lista_status,
                                new { @class = "form-control" }
                            )
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Observacao, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Observacao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Observacao, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <input type="submit" value="Salvar" class="btn btn-success btn-block" />
                </div>
            </div>
        }
    </div>
</div>
<div>
    @Html.ActionLink("Voltar à lista", "Index")
</div>

InventarioIFSP/InventarioIFSP/Views/Item/Details.cshtml
@model InventarioIFSP.Models.Item

@{
    ViewBag.Title = "Detalhes do item";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row justify-content-center">
    <h2>@ViewBag.Title</h2>
</div>

@{
    if (TempData["msg"] != null)
    {
        <div class="alert alert-@TempData["msg_type"] text-center">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            @TempData["msg"]
        </div>
    }

}

<div class=" row justify-content-center">
    <div class="col-10">
        <div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Patrimonio, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Patrimonio, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor( model => model.Categoria.Nome, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                    </div>
                    <div class="form-group">
                        @*@Html.LabelFor(model => model.Localidade, htmlAttributes: new { @class = "control-label" })*@
                        <label class="control-label" for="localidade">Localização</label>
                        @Html.EditorFor(model => model.Localidade.Nome, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Status.Nome, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Observacao, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Observacao, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                    </div>
                    <p>
                        @Html.ActionLink("Alterar", "Edit", new { id = Model.ID }, new { @class = "btn btn-primary btn-block" })
                    </p>
                </div>
            }
        </div>
    </div>

</div>
<p>
    @Html.ActionLink("Voltar à lista", "Index", "Item", null, new { })
</p>

InventarioIFSP/InventarioIFSP/Views/Item/Edit.cshtml
@model InventarioIFSP.Models.Item

@{
    ViewBag.Title = "Alterar item";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row justify-content-center">
    <h2>@ViewBag.Title</h2>
</div>

@{
    if (TempData["msg"] != null)
    {
        <div class="alert alert-@TempData["msg_type"] text-center">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            @TempData["msg"]
        </div>
    }

}
<div class=" row justify-content-center">
    <div class="col-10">
        <div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Patrimonio, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Patrimonio, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Patrimonio, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownListFor(
                                model => model.Categoria.ID,
                                InventarioIFSP.Database.ItemCategoriaDAO.lista_categorias,
                                new { @class = "form-control" }
                            )
                        @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @*@Html.LabelFor(model => model.Localidade, htmlAttributes: new { @class = "control-label" })*@
                        <label class="control-label" for="localidade">Localização</label>
                        @Html.DropDownListFor(
                                model => model.Localidade.ID,
                                InventarioIFSP.Database.LocalidadeDAO.lista_localidades,
                                new { @class = "form-control" }
                            )
                        @Html.ValidationMessageFor(model => model.Localidade, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label" })
                        @Html.ActionLink("+", "Create", "ItemStatus", null, new { @class = "btn btn-sm btn-primary" })
                        @Html.DropDownListFor(
                                model => model.Status.Id,
                                InventarioIFSP.Database.ItemStatusDAO.lista_status,
                                new { @class = "form-control" }
                            )
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Observacao, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Observacao, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Observacao, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Salvar" class="btn btn-success btn-block" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<div>
    @Html.ActionLink("Voltar à lista", "Index")
</div>