InventarioIFSP/InventarioIFSP/Models/RelatorioController.cs
using InventarioIFSP.Database;
using InventarioIFSP.ReportFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventarioIFSP.Models
{
    public class RelatorioController : Controller
    {
        // GET: Relatorio
        public ActionResult Index()
        {
            LocalidadeDAO.AtualizaLocalidades();
            ItemCategoriaDAO.AtualizaCategorias();
            ItemStatusDAO.AtualizaTiposStatus();
            LocalidadeCategoriaDAO.AtualizaCategorias();
            return View();
        }


        public ActionResult GenerateReportTest(ReportFiltersViewModel rep)
        {
            string SQL = "SELECT " +
                                "l.nome AS Localidade, " +
                                "i.patrimonio AS Patrimonio, " +
                                "c.nome AS Categoria, " +
                                "s.nome AS Status " +
                            "FROM " +
                                "localidade l INNER JOIN item i on l.id = i.localidade " +
                                "INNER JOIN item_categoria c ON c.id = i.categoria " +
                                "INNER JOIN item_status s ON s.id = i.status";


            string WHERE= " ";
            bool GotBeforeFilter = false;

            if (rep.LOC.ID > 0 || rep.ITEMCAT.ID > 0 || rep.STA.Id > 0)
            {
                WHERE += " WHERE ";

                if (rep.LOC.ID > 0)
                {
                    WHERE += " l.id = " + rep.LOC.ID;
                    GotBeforeFilter = true;
                }

                if (rep.ITEMCAT.ID > 0)
                {
                    if (GotBeforeFilter)
                        WHERE += " AND ";

                    WHERE += " c.id = " + rep.ITEMCAT.ID;

                    GotBeforeFilter = true;
                }

                if (rep.STA.Id > 0)
                {
                    if (GotBeforeFilter)
                        WHERE += " AND ";

                    WHERE += " s.id = " + rep.STA.Id;
                }
            }


            string ORDER= " ORDER BY 1,3,4"; // implementar opção para o usuário escolher via DropDownList

            SQL += WHERE + ORDER;

            List<string> fields = new List<string>();
            fields.Add("Localidade");
            fields.Add("Patrimonio");
            fields.Add("Categoria");
            fields.Add("Status");

            Relatorio rel = new Relatorio(
                    SQL, 
                    4,
                    fields,
                    "Itens", 
                    "Listagem de itens", 
                    ""
                );

            return rel.GenerateReport();
        }
    }
}

InventarioIFSP/InventarioIFSP/Controllers/ItemController.cs
using InventarioIFSP.Database;
using InventarioIFSP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventarioIFSP.Controllers
{
    public class ItemController : Controller
    {

        [HttpGet]
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }
        
        [HttpGet]
        public ActionResult Create()
        {
            // Início: Proteção de rota
            if (Session["usuario_nivel"] == null)
            {
                TempData["msg"] = "Necessário estar logado!";
                TempData["msg_type"] = "warning";
                return RedirectToAction("Index", "Home");
            }

            if (Convert.ToInt32(Session["usuario_nivel"]) > 1)
            {
                TempData["msg"] = "Você não tem autorização para acessar esta área!";
                TempData["msg_type"] = "danger";
                return RedirectToAction("Index", "Home");
            }
            // Fim: Proteção de Rota

            LocalidadeDAO.AtualizaLocalidades();
            ItemCategoriaDAO.AtualizaCategorias();
            ItemStatusDAO.AtualizaTiposStatus();
            return View();
        }

        [HttpPost]
        public ActionResult Create(Item item)
        {
            // Início: Proteção de rota
            if (Session["usuario_nivel"] == null)
            {
                TempData["msg"] = "Necessário estar logado!";
                TempData["msg_type"] = "warning";
                return RedirectToAction("Index", "Home");
            }

            if (Convert.ToInt32(Session["usuario_nivel"]) > 1)
            {
                TempData["msg"] = "Você não tem autorização para acessar esta área!";
                TempData["msg_type"] = "danger";
                return RedirectToAction("Index", "Home");
            }
            // Fim: Proteção de Rota

            try
            {
                try
                {
                    if (item.Observacao.Equals(string.Empty)) { }
                }
                catch (Exception)
                {
                    string str = "";
                    item.Observacao = str;
                }
                if(ItemDAO.Create(item) != null)
                {
                    TempData["msg"] = "Criado com sucesso!";
                    TempData["msg_type"] = "success";
                    return RedirectToAction("Index");
                }
            }
            catch
            {
            }
            TempData["msg"] = "Erro ao criar!";
            TempData["msg_type"] = "danger";
            return View();
        }

        [HttpGet]
        public ActionResult List()
        {
            // Início: Proteção de rota
            if (Session["usuario_nivel"] == null)
            {
                TempData["msg"] = "Necessário estar logado!";
                TempData["msg_type"] = "warning";
                return RedirectToAction("Index", "Home");
            }

            if (Convert.ToInt32(Session["usuario_nivel"]) > 1)
            {
                TempData["msg"] = "Você não tem autorização para acessar esta área!";
                TempData["msg_type"] = "danger";
                return RedirectToAction("Index", "Home");
            }
            // Fim: Proteção de Rota

            try
            {
                LocalidadeDAO.AtualizaLocalidades();
                ItemCategoriaDAO.AtualizaCategorias();
                ItemStatusDAO.AtualizaTiposStatus();
                List<Item> lista = ItemDAO.GetAll();
                TempData["lista_status"] = ItemStatusDAO.lista_status;
                return View(lista);
            }
            catch
            {
                TempData["msg"] = "Erro ao buscar dados!";
                TempData["msg_type"] = "danger";
                return View();
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            // Início: Proteção de rota
            if (Session["usuario_nivel"] == null)
            {
                TempData["msg"] = "Necessário estar logado!";
                TempData["msg_type"] = "warning";
                return RedirectToAction("Index", "Home");
            }

            if (Convert.ToInt32(Session["usuario_nivel"]) > 1)
            {
                TempData["msg"] = "Você não tem autorização para acessar esta área!";
                TempData["msg_type"] = "danger";
                return RedirectToAction("Index", "Home");
            }
            // Fim: Proteção de Rota

            try
            {
                LocalidadeDAO.AtualizaLocalidades();
                ItemCategoriaDAO.AtualizaCategorias();
                ItemStatusDAO.AtualizaTiposStatus();
                Item item = ItemDAO.GetByID(id);
                if (item != null)
                {
                    return View(item);
                }
            }
            catch (Exception)
            {
            }
            TempData["msg"] = "Erro ao buscar dados!";
            TempData["msg_type"] = "danger";
            return View();
        }

        [HttpPost]
        public ActionResult Edit(Item item)
        {
            // Início: Proteção de rota
            if (Session["usuario_nivel"] == null)
            {
                TempData["msg"] = "Necessário estar logado!";
                TempData["msg_type"] = "warning";
                return RedirectToAction("Index", "Home");
            }

            if (Convert.ToInt32(Session["usuario_nivel"]) > 1)
            {
                TempData["msg"] = "Você não tem autorização para acessar esta área!";
                TempData["msg_type"] = "danger";
                return RedirectToAction("Index", "Home");
            }
            // Fim: Proteção de Rota

            try
            {
                try
                {
                    if (item.Observacao.Equals(string.Empty)) { }
                }
                catch (Exception)
                {
                    string str = "";
                    item.Observacao = str;
                }
                if (ItemDAO.Update(item))
                {
                    TempData["msg"] = "Atualizado com sucesso!";
                    TempData["msg_type"] = "success";
                    return RedirectToAction("Index");
                }
            }
            catch
            {
            }
            TempData["msg"] = "Erro ao buscar dados!";
            TempData["msg_type"] = "danger";
            return View();
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            // Início: Proteção de rota
            if (Session["usuario_nivel"] == null)
            {
                TempData["msg"] = "Necessário estar logado!";
                TempData["msg_type"] = "warning";
                return RedirectToAction("Index", "Home");
            }

            if (Convert.ToInt32(Session["usuario_nivel"]) > 1)
            {
                TempData["msg"] = "Você não tem autorização para acessar esta área!";
                TempData["msg_type"] = "danger";
                return RedirectToAction("Index", "Home");
            }
            // Fim: Proteção de Rota

            try
            {
                if (ItemDAO.Delete(id))
                {
                    TempData["msg"] = "Atualizado com sucesso!";
                    TempData["msg_type"] = "success";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
            }
            TempData["msg"] = "Erro ao excluir!";
            TempData["msg_type"] = "danger";
            return RedirectToAction("Index");
        }

        // Esta action recebe os dados do ajax para atualizar os dados do inventario
        [HttpPost]
        public ActionResult AtualizaStatus()
        {
            int id = Convert.ToInt32(Request["id"]);
            int status = Convert.ToInt32(Request["status"]);
            Item item = ItemDAO.GetByID(id);
            item.Status.Id = status;
            if (ItemDAO.Update(item))
            {
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }

        // Esta action recebe os dados do ajax para atualizar os dados do inventario
        [HttpPost]
        public ActionResult AtualizaObs()
        {
            int id = Convert.ToInt32(Request["id"]);
            string observacao = Request["observacao"];
            Item item = ItemDAO.GetByID(id);
            item.Observacao = observacao;
            if (ItemDAO.Update(item))
            {
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Details(int id)
        {
            // Início: Proteção de rota
            if (Session["usuario_nivel"] == null)
            {
                TempData["msg"] = "Necessário estar logado!";
                TempData["msg_type"] = "warning";
                return RedirectToAction("Index", "Home");
            }

            if (Convert.ToInt32(Session["usuario_nivel"]) > 1)
            {
                TempData["msg"] = "Você não tem autorização para acessar esta área!";
                TempData["msg_type"] = "danger";
                return RedirectToAction("Index", "Home");
            }
            // Fim: Proteção de Rota
            try
            {
                Item item = ItemDAO.GetByID(id);
                return View("Details", item);
            }
            catch (Exception)
            {
                TempData["msg"] = "Erro ao buscar dados!";
                TempData["msg_type"] = "danger";
                return View();
            }
            
        }

InventarioIFSP/InventarioIFSP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - INVENTÁRIO CAE IFSP-PRC</title>
    @Styles.Render("~/Content/bootstrap.min.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
   
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        @*@Html.ActionLink("INVENTÁRIO CAE IFSP, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
        <a href="/" class="navbar-brand"><img src="~/Resources/logo-icon-100x100.png" width="30"/> Inventário</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="container-fluid align-content-end align-self-end">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("Início", "Index", "Home", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Sobre", "About", "Home", null, new { @class = "nav-link" })
                    </li>
                    @if (Session["usuario_nome"] != null) // aqui verifica se está logado
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="localidade_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Inventário
                            </a>
                            <div class="dropdown-menu" aria-labelledby="localidade_dropdown">
                                @Html.ActionLink("Atualizar", "SelecionaLocalidade", "Inventario", null, new { @class = "nav-link" })
                                @Html.ActionLink("Inventários", "Inventario", "Inventario", null, new { @class = "nav-link" })
                            </div>
                        </li>
                        if (Convert.ToInt32(Session["usuario_nivel"]) < 2)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="item_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Localizações
                                </a>
                                <div class="dropdown-menu" aria-labelledby="item_dropdown">
                                    @Html.ActionLink("Localizações", "Index", "Localidade", null, new { @class = "nav-link" })
                                    @Html.ActionLink("Categorias", "Index", "LocalidadeCategoria", null, new { @class = "nav-link" })
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="item_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Itens
                                </a>
                                <div class="dropdown-menu" aria-labelledby="item_dropdown">
                                    @Html.ActionLink("Itens", "Index", "Item", null, new { @class = "nav-link" })
                                    @Html.ActionLink("Categorias", "Index", "ItemCategoria", null, new { @class = "nav-link" })
                                    @Html.ActionLink("Status", "Index", "ItemStatus", null, new { @class = "nav-link" })
                                </div>
                            </li>
                            @*<li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="relatorio_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Relatórios
                                </a>
                                <div class="dropdown-menu" aria-labelledby="relatorio_dropdown">
                                    @Html.ActionLink("Relatórios", "Index", "Relatorio", null, new { @class = "nav-link" })
                                </div>
                            </li>*@
                        }
                        if (Convert.ToInt32(Session["usuario_nivel"]) < 1)
                        {
                            <li class="nav-item">
                                @Html.ActionLink("Usuários", "Index", "Usuario", null, new { @class = "nav-link" })
                            </li>
                        }
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="usuario_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Olá, @Session["usuario_nome"]
                            </a>
                            <div class="dropdown-menu" aria-labelledby="usuario_dropdown">
                                @Html.ActionLink("Minha conta", "MyData", "Usuario", null, new { @class = "dropdown-item" })
                                @Html.ActionLink("Sair", "Logout", "Usuario", null, new { @class = "dropdown-item" })
                            </div>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Login", "Login", "Usuario", null, new { @class = "nav-link" })
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>&copy; @DateTime.Now.Year - INVENTÁRIO CAE IFSP-PRC</p>
        </footer>
    </div>

    @Scripts.Render("~/Scripts/jquery-3.2.1.min.js")
    @Scripts.Render("~/Scripts/popper.min.js")
    @Scripts.Render("~/Scripts/bootstrap.min.js")
    @Scripts.Render("~/Scripts/main.js")
    
    @RenderSection("scripts", required: false)
</body>
</html>

InventarioIFSP/InventarioIFSP/Views/Shared/_ReportLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - INVENTÁRIO CAE IFSP-PRC</title>
    @Styles.Render("~/Content/bootstrap.min.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container-fluid body-content">
        <div class="row justify-content-center">
            <div class="col-10">
                <img src="~/Resources/logo-full-960x480.png" width="200"/>
            </div>
            
        </div>
        @RenderBody()
    </div>

    @Scripts.Render("~/Scripts/jquery-3.2.1.min.js")
    @Scripts.Render("~/Scripts/popper.min.js")
    @Scripts.Render("~/Scripts/bootstrap.min.js")
    @Scripts.Render("~/Scripts/main.js")

    @RenderSection("scripts", required: false)
</body>
</html>